### ISSUE TITLE
Remove run-as-user command because it is also the entrypoint

### ISSUE THREAD

**Issue by dagomar** [mkenney/docker-npm#141]
I found that when using the provided shell scripts the docker container fails to run the desired command. Instead the command that is send to the container is:

`/run-as-user /run-as-user /usr/local/bin/{script} [...]`

I was able to see with 'top' that the above was the command which was running without ever finishing. Removing the /run-as-user from the shell scripts worked for me. I have created a pull request with the changes:

#140

**Comment by mkenney** [comment]
Done!
