### ISSUE TITLE
Feature request: add npx so we can easily use global packages without installing them

### ISSUE THREAD

**Issue by dagomar** [mkenney/docker-npm#143]
Hi, 

Locally I have this Dockerfile:

`
FROM mkenney/npm:node-8-alpine
RUN npm install --silent -g npx
`

I've adapted a shell script in similar fashion to the ones in this repo, but which uses my local Dockerfile build for npx.  Npx is great because it allows us to run global npm scripts without installing them. For instance to create a react project this would be:

`npx create-react-app my-app`

This works beautifully. I have a pull request (#142) which adds this to the repository. Potentially a nice addition for this would be to allow npx to install the scripts in a specified folder under the users $HOME, so that it doesn't need to download everything every time you run the command, which would enhance the speed greatly. Very curious about your thoughts.

**Comment by mkenney** [comment]
Hi,

I'm not familiar with `npx` but it looks interesting. I'll do a bit more reading but can you describe how the part about caching the packages in $HOME works? Would that be driven by a `npx` configuration file or something?

**Comment by dagomar** [comment]
Hi @mkenney,

npx is also new for me, but I understood it is possible to set a location for global files through the cli; it allows to specify the location of the npm cache by passing --cache. The docker command could then be something like:

`docker run --rm -$term_type -v $(pwd):/src:rw -v $HOME/.ssh:/home/dev/.ssh:ro -v $HOME/{THE_CACHE_DIRECTORY}:/path/to/cache mkenney/npm:$TAG /run-as-user /usr/local/bin/$SCRIPT $@`

Actually, come to think of it, it looks like it is not necessary to pass anything extra to npx, just mounting the right folder to the npm cache should work I think. 

I'd need to do a bit more investigation on this though. I think it would need to be optional, so I'm uncertain how this would work best in the setup of your project, if it would be done by setting an environment variable or something else. If you like I can look into it and see if I can make it part of this, or we could do it seperately after this lands.

**Comment by mkenney** [comment]
Ok, that makes sense. If you have any thoughts around how to implement that, that would be great. I'd be open to an environment variable with a sane default that mounts to `$HOME/.npx` or whatever the standard location is. I would expect that users who execute `npx` would like it to cache things automatically by default.

**Comment by mkenney** [comment]
Related threads: #166, #167

**Comment by mkenney** [comment]
@dagomar, @jgoux, this has been released. I also included changes for #166 and #167. To resolve #166 (and the cache issue here) I added mounting `$HOME/.npm` to all of the scripts. 

Please take a look at the updated scripts and [latest tags on hub.docker.com](https://hub.docker.com/r/mkenney/npm/tags/) and let me know if you have any problems. Thank you!

**Comment by mkenney** [comment]
Closing, feel free to reopen.
