### ISSUE TITLE
how can i forward env varriables to container??

### ISSUE THREAD

**Issue by luchnck** [mkenney/docker-npm#148]
` docker run -e "deep=purple" --rm mkenney/npm env`
produces 
`LANGUAGE=C.UTF-8`
...
`SUDO_USER=root`
`SUDO_UID=0`
`SUDO_GID=0`
`

but where is no "deep" environment varriable, what i do wrong???

**Comment by mkenney** [comment]
Hi @luchnck,

It depends on what you're trying to do. The reason you can't see it with that command is that the image entrypoint runs commands in a subshell (to prevent outputting files as `root` in Linux dev environments) so your environment variable is set but the user that's running commands can't see it.

What are you trying to accomplish?

**Comment by luchnck** [comment]
I want  to specify api server as proxy (another container witch ip assigns dynamicaly) in my webpackDevServer, but can't see it varriable in process.env in node

**Comment by mkenney** [comment]
I think this is probably the wrong approach to what you want to do. The dynamic networking in docker is tricky and should be handled by docker. Instead, you should create a user-defined network and have your containers use it.

to create a network:
```
docker network create --driver bridge mynetwork
```

then when starting your containers, name them and attach them to the network
```
docker run -d --name myproxy --network mynetwork myimage/server
docker run -d --name myapp --network mynetwork myimage/app
```

Then you can just tell webpack to connect to `myproxy` and docker will do the DNS work for you.

You can also use [`docker-compose`](https://docs.docker.com/compose/) to start your applications and it will automate the networking for you.

Does that help?

**Comment by luchnck** [comment]
Ok) I can't use env vars with ENTRYPOINT command, so, it must works if I pass varriable as argument of node script. I Will try, thanks for answers

**Comment by luchnck** [comment]
> I think this is probably the wrong approach to what you want to do. The dynamic networking in docker is tricky and should be handled by docker. Instead, you should create a user-defined network and have your containers use it.
> 
> to create a network:
> 
> ```
> docker network create --driver bridge mynetwork
> ```
> then when starting your containers, name them and attach them to the network
> 
> ```
> docker run -d --name myproxy --network mynetwork myimage/server
> docker run -d --name myapp --network mynetwork myimage/app
> ```
> Then you can just tell webpack to connect to `myproxy` and docker will do the DNS work for you.
> 
> You can also use [`docker-compose`](https://docs.docker.com/compose/) to start your applications and it will automate the networking for you.
> 
> Does that help?

Yes, that's one of the way, may be it's more simple, but I used package.json->config features for specify my variables and run container with command:
docker run \
    --rm \
    -it \
...
    -e "PUID=500" \
    -e "PGID=500" \
    -p 3000:3000 \
   mkenney/npm:latest npm \
   start --my-package:apiServer=http://$API_SERVER_ADDR`

May be it wiil be useful for somelse..
Thanks! 
Closed

**Comment by mkenney** [comment]
@luchnck,

You _can_ override the entrypoint and the environment variables will work normally, but the `PUID` and `PGID` variables will be ignored and the user that runs the process will be `root`. That's usually ok with docker but it can make development a pain in linux when you have to `sudo` to delete files.

To remove the entrypoint completely, just add `--entrypoint=""`, so this will work:
```
$ docker run --rm -ti --entrypoint="" -e "deep=purple" mkenney/npm env | grep deep
deep=purple
```

Or you can set it to something more applicable to your application, so in your example, this should work too:
```
docker run 
--rm 
-it 
--entrypoint=npm
...
-e "PUID=500" 
-e "PGID=500" 
-e "API_SERVER_ADDR=172.20.0.2"
-p 3000:3000 
mkenney/npm:latest
start --my-package:apiServer=http://$API_SERVER_ADDR
```

**Comment by luchnck** [comment]
Yes, thanks for that decision!
