### ISSUE TITLE
Npm and Yarn cache

### ISSUE THREAD

**Issue by jgoux** [mkenney/docker-npm#166]
Hello,

Thanks for this awesome project, I started working on dockerizing my dev environment and I found your repo! 😄 

Would it be possible to add an option to enable caching for both npm and yarn commands ?

I think it would require to mount another volume where the cache folder is expected for both tools.

**Comment by mkenney** [comment]
[Done](https://github.com/mkenney/docker-npm/blob/master/bin/npm#L24), please let me know if you have any trouble, thanks!

**Comment by mkenney** [comment]
Closing, feel free to reopen.
