### ISSUE TITLE
Build tools are missing

### ISSUE THREAD

**Issue by VeeeneX** [mkenney/docker-npm#17]
I can't use sass because alpine npm is missing built tools, so I've used https://github.com/gliderlabs/docker-alpine/issues/24 alpine-sdk.

**Comment by mkenney** [comment]
Hi @VeeeneX,

The build tools are available in the `debian` branch/tag, please see the [change log for 2016-09-17](https://github.com/mkenney/docker-npm#change-log). The `latest` image has been replaced with the alpine version because the image is 80% smaller. Thanks!
