### ISSUE TITLE
Build tools in `alpine` images

### ISSUE THREAD

**Issue by mkenney** [mkenney/docker-npm#39]
I have been leaving the build tools (`gcc`, `g++`, `make`, etc.) out of the `alpine` images to reduce the overall image size, however I find that most of the issues I have that trace back to the image itself have to do with missing build tools and on many projects I end up using the `debian` based image anyway.

As it has also caused problems for others (#9, #17, #18) I may add those tools back in to the image in the near future and I'm not sure how much it will add to the image (50 - 100MB or so I would guess). Please let me know if anyone has any concerns with that.

@arnested @NewOldMax @VeeeneX

**Comment by VeeeneX** [comment]
I think it will be almost the same as debian image, although give it a try.

**Comment by mkenney** [comment]
It looks like it adds [~45MB](https://hub.docker.com/r/mkenney/npm/tags/) increasing the compressed image size to 116MB.

**Comment by mkenney** [comment]
Done, merged https://github.com/mkenney/docker-npm/pull/53 and https://github.com/mkenney/docker-npm/pull/54
