### ISSUE TITLE
browserSync has trouble when connecting to the external IP

### ISSUE THREAD

**Issue by bretmette** [mkenney/docker-npm#7]
I am seeing a bit of unexpected and unpredictable behavior when using browserSync on the external IP. Aside from the issue with the WordPress redirect I am also seeing odd behavior in that some connections are refused (especially when coming in quickly, loading a page, etc).

Other times I just get a crash with little information other than --

```
ERROR: dial unix /Users/bmette/Library/Containers/com.docker.docker/Data/*00000003.00000948: connect: connection refused
```

**Comment by mkenney** [comment]
Does this still happen, or have you found a workaround?

**Comment by bretmette** [comment]
@mkenney Still happening. The gulp container dies (maybe a memory issue or maybe something to do with all the proxying going on that may not be properly configured).

It happens even when I do not connect from an external browser, seems to happen more often when many connections are made to the gulp container.

Have not found any solution yet, it doesn't happen often enough to force me to make it a priority, but I would still like to solve it in the near future.

Also I am not sure if it is related, but I do get a lot of dropped connections when connecting through my workstation's external IP (i.e. from another device on the local network).

**Comment by bretmette** [comment]
@mkenney I am leaning towards a memory issue, as I have seen this happen even when I am more or less "idle". Browsersync does constantly poll the gulp container to make sure it is still connected so that may be why it dies even when I am not actively developing.

**Comment by mkenney** [comment]
Ok, I'll close this for now.
