### ISSUE TITLE
Add GID and UID environment variables to the wrapper script

### ISSUE THREAD

**Issue by mkenney** [mkenney/docker-npm#93]
Someone has requested being able to define the UID and GID values via environment variables instead of always basing them on `/src` or `~/.ssh`, ala https://hub.docker.com/r/linuxserver/plex/ which uses `-e PUID=<id> -e PGID=<id>`. I think it's a nice enhancement so I'll probably just do it the same way.

**Comment by mkenney** [comment]
@bskrtich

**Comment by hskrtich** [comment]
Thank you!

**Comment by mkenney** [comment]
Here's the PR: https://github.com/mkenney/docker-scripts/pull/1

**Comment by mkenney** [comment]
The builds are running now https://travis-ci.org/mkenney/docker-npm
